backend:
  name: github
  repo: iwolz/mlf-site
  branch: main

media_folder: "images"

collections:
  - name: "posts"
    label: "Posts"
    folder: "posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Tag", name: "tag", widget: "select", options: ["Engineering", "Payments", "Career", "Books", "Learning"] }
      - { label: "Body", name: "body", widget: "markdown" }
